import type { Metadata } from "next";

import "../globals.css";

import NavBar from "../components/layout/navbar/NavBar";

export const metadata: Metadata = {
  title: "Ecommerce Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div>
      <NavBar title="" />
      {children}
    </div>
  );
}
